name: Lint

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

jobs:
  php:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']

    name: php${{ matrix.php-versions }} lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up php${{ matrix.php-versions }}
        uses: shivammathur/setup-php@2.18.1
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Lint
        run: composer run lint

  php-cs-fixer:
    name: php-cs check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up php
      uses: shivammathur/setup-php@2.18.1
      with:
        php-version: 7.4
        coverage: none
    - name: Install dependencies
      run: composer i
    - name: Run coding standards check
      run: composer run cs:check
